#BAN_IPV4_SUBNET=/32
#BAN_IPV6_SUBNET=/64
#DEBUG=1
#DEFAULT_NFT_BLACK4=black4
#DEFAULT_NFT_BLACK6=black6
#DEFAULT_NFT_TABLE_PREFIX=ban-
#DEFAULT_NFT_TABLE_TYPE=inet
#DEFAULT_NFT_WHITE4=white4
#DEFAULT_NFT_WHITE6=white6
#DEFAULT_WHITE4_SUFFIX=-white4.txt
#DEFAULT_WHITE6_SUFFIX=-white6.txt
#FILE_NFT_RULES_SUFFIX=.nft
#FILE_SETTINGS_SUFFIX=.conf

SERVICE_PORT=22
